title: GenApex Enterprise Evolution
description: Innovative AI-powered consulting and digital solutions for governments and public utilities.
author: Alonso Perez

# Development settings
baseurl: ""
url: "https://genapex.org/" # Development URL - change to your production URL when deploying

# Contact information
email: sales@GenApex.org
phone: "+1 (647) 366-9844" # Update with your actual phone number
address: "123 Innovation Ave, Suite 200, Toronto, ON" # Update with actual address

# Social media
social:
  linkedin: https://linkedin.com/company/genapex # Update with actual URL
  twitter: https://twitter.com/genapex # Update with actual URL

# Brand settings
color-scheme: "#575f00" # the scheme can be any HEX code like "#00aa55" Used ginko leaves color palette
logo: /assets/img/GENAPEX-logo (2).jpg

# SEO settings
lang: en
keywords: AI, digital transformation, government, public utilities, strategic planning, process optimization

# Theme settings
theme: minima

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown

# Plugin settings
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
