# .github/workflows/jekyll.yml
name: Jekyll Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - run: |
          gem install jekyll -v 4.3.3
          gem install jekyll-seo-tag -v 2.8.0
          bundle exec jekyll build
      - uses: actions/upload-pages@v3
